baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'MAHcodes'

[menus]
[[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 10
[[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 20
[[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 30
